import "@/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { ThemeProvider } from "@/components/theme-provider";
import { RESIZABLE_LAYOUT_COOKIE } from "@/constants/layout";
import { cn } from "@/lib/utils";
import { TRPCReactProvider } from "@/trpc/react";

import ResizablePanelLayout from "./_components/resizable-panel-layout";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children?: React.ReactNode;
}) {
  const layout = cookies().get(RESIZABLE_LAYOUT_COOKIE);

  const defaultLayout: [number, number] | undefined = layout
    ? (JSON.parse(layout.value) as [number, number])
    : undefined;

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable,
        )}
      >
        <TRPCReactProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ResizablePanelLayout defaultLayout={defaultLayout}>
              <main className="flex h-screen flex-col items-center justify-center">
                {children}
              </main>
            </ResizablePanelLayout>
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
